print("Name: Peter Sutton")
print("ID: 1958376")
print("Phone: 317-627-0208")
print("Department: Loyola Notre Dame Library")
print("Grade: Graduate Certificate")
print("Github link:https://github.com/peterbucksutton/Week-1")