Print("Name: Peter Sutton")
Print("ID: 1958376")
Print("Phone: 317-627-0208")
Print("Department: Loyola Notre Dame Library")
Print("Grade: Graduate Certificate")
Print("Github link:https://github.com/peterbucksutton/Week-1")